---

services:
  python:
    # Build with: ./scripts/build.sh (required for Linux with AppArmor)
    # See: https://github.com/dani-garcia/vaultwarden/discussions/3800
    tty: true
    command: ["python", "main.py"]

  influxdb:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb2
      - ./docker/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=switchbot
